# Generated by Django 3.0.7 on 2020-06-24 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('canteen_managemant_system', '0002_auto_20200624_1922'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='cook',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='canteen_managemant_system.Cook'),
        ),
    ]
