# Generated by Django 3.0.7 on 2020-06-25 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('canteen_managemant_system', '0003_auto_20200624_1923'),
    ]

    operations = [
        migrations.CreateModel(
            name='CookInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_no', models.CharField(max_length=12)),
                ('pan_no', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='cook',
            name='info',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='canteen_managemant_system.CookInfo'),
        ),
    ]
