# Generated by Django 3.0.7 on 2020-06-25 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canteen_managemant_system', '0005_speciality'),
    ]

    operations = [
        migrations.AddField(
            model_name='cook',
            name='profile_pic',
            field=models.ImageField(null=True, upload_to='cook'),
        ),
    ]
